modLoader = "kotlinforforge"
loaderVersion = "[3.12.0,)"
issueTrackerURL = "https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues"
license = "Apache-2.0"

[[mods]]
modId = "vs_tournament"
version = "${version}"
displayName = "VS Tournament Mod"
authors = [
    "alex_s168",
    "ConstantDust",
    "Illuc",
    "Percant Pie"
]
description = '''

'''

[[dependencies.vs_tournament]]
modId = "forge"
mandatory = true
versionRange = "[40.2.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_tournament]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_tournament]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[${vs2_version},)"
ordering = "AFTER"
side = "BOTH"
